manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ftc
    - name: refil
      url-base: https://github.com/ryancolinoconnor
  projects:
    - name: zmk
      remote: refil
      revision: adv360-z3-mb
      import: app/west.yml
  self:
    path: config
