manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/DelusionalLogic
    - name: refil
      url-base: https://github.com/refil
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mouse0buttons
      import: app/west.yml
  self:
    path: config
